'use strict';
// AAAS 사용자 UI 시안. 모든 검색·분석·법령 내용은 예시이며 외부 AI/API를 호출하지 않습니다.
const U = (() => {
const $ = s => document.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={
 panel:'M3 4h18v16H3z M9 4v16',edit:'M14 4 20 10 M4 20l5-1L21 7a2 2 0 0 0-4-4L5 15z M13 3H3v18h18v-8',
 search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14 m5 12 6 6',spark:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3z',
 file:'M5 3h9l5 5v13H5z M14 3v6h5 M8 13h8 M8 17h6',scale:'M12 3v17 M7 21h10 M4 6h16 M6 6l-4 8h8z M18 6l-4 8h8z',
 clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 7v5l3 2',settings:'M4 6h16 M4 12h16 M4 18h16 M8 3v6 M16 9v6 M10 15v6',
 bell:'M18 8a6 6 0 0 0-12 0c0 8-3 7-3 10h18c0-3-3-2-3-10 M10 21h4',upload:'M12 16V3 m-5 5 5-5 5 5 M4 14v7h16v-7',
 plus:'M12 5v14 M5 12h14',arrow:'M12 20V4 m-6 6 6-6 6 6',chevron:'m9 5 7 7-7 7',close:'m6 6 12 12 M6 18 18 6',
 link:'m9 8 3-3a5 5 0 0 1 7 7l-3 3 M15 16l-3 3a5 5 0 0 1-7-7l3-3 M8 16l8-8',shield:'m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6z m-4 10 3 3 5-6',
 filter:'M3 5h18l-7 8v6l-4 2v-8z',refresh:'M20 7a8 8 0 0 0-14-2L3 8 M3 3v5h5 M4 17a8 8 0 0 0 14 2l3-3 M21 21v-5h-5',
 compare:'M9 3H3v18h6 M15 3h6v18h-6 M12 2v20',copy:'M8 8h13v13H8z M16 8V3H3v13h5',bookmark:'M6 3h12v18l-6-4-6 4z',
 trash:'M3 6h18 M6 6v15h12V6 M9 6V3h6v3 M10 10v7 M14 10v7',check:'m5 12 4 4L19 6',info:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 11v6 M12 7v1',
 book:'M12 5c-4-3-8-2-10-1v15c4-2 7-1 10 1 3-2 6-3 10-1V4c-2-1-6-2-10 1v15',grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',
 stop:'M6 6h12v12H6z',alert:'m12 3 10 18H2z M12 9v5 M12 17v1',download:'M12 3v13 m-5-5 5 5 5-5 M4 16v5h16v-5',menu:'M3 6h18 M3 12h18 M3 18h18',
};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[n]||icons.file}"/></svg>`;
const btn=(label,action,ico='plus',style='',id='')=>`<button type="button" class="btn ${style}" data-action="${action}" ${id?`data-id="${esc(id)}"`:''}>${icon(ico)}${label}</button>`;
const pill=(label,color='blue')=>`<span class="pill ${color}">${esc(label)}</span>`;
const guardrail='AAAS의 응답은 참고 자료이며, 심판관의 최종 법적 판단을 대체하지 않습니다.';
const samples=[
 {id:'case-1',no:'제2023-018호',title:'석유제품운반선 한울호·어선 해성호 충돌사건',type:'충돌',cause:'경계 소홀',vessel:'유조선·어선',issues:'경계 소홀 · 충돌위험 판단',law:'국제해상충돌예방규칙',articles:'제5조 경계 · 제7조 충돌위험',score:94,office:'부산지방해양안전심판원',date:'2023.06.15',pages:12,file:'부산해심_제2023-018호_재결서.pdf'},
 {id:'case-2',no:'제2022-041호',title:'석유제품운반선 해진호·어선 동명호 충돌사건',type:'충돌',cause:'피항협력 미흡',vessel:'석유제품운반선·어선',issues:'피항협력 미흡 · AIS 확인 소홀',law:'국제해상충돌예방규칙',articles:'제8조 충돌을 피하기 위한 동작',score:91,office:'인천지방해양안전심판원',date:'2022.11.09',pages:15,file:'인천해심_제2022-041호_재결서.pdf'},
 {id:'case-3',no:'제2023-027호',title:'화물선 동해프라이드호·어선 청해호 충돌사건',type:'충돌',cause:'당직근무 부적절',vessel:'화물선·어선',issues:'당직근무 부적절 · 레이더 감시 미흡',law:'해사안전 관련 법령',articles:'항해당직 및 안전운항 관련 조항',score:88,office:'동해지방해양안전심판원',date:'2023.08.22',pages:10,file:'동해해심_제2023-027호_재결서.pdf'},
 {id:'case-4',no:'제2024-009호',title:'유조선 태성호·어선 제8서진호 충돌사건',type:'충돌',cause:'안전속력 미준수',vessel:'유조선·어선',issues:'안전속력 유지 의무 · 제한 시계',law:'국제해상충돌예방규칙',articles:'제6조 안전속력',score:86,office:'목포지방해양안전심판원',date:'2024.03.11',pages:14,file:'목포해심_제2024-009호_재결서.pdf'},
 {id:'case-5',no:'제2024-015호',title:'화물선 동해스타호 좌초사건',type:'좌초',cause:'항로 확인 미흡',vessel:'화물선',issues:'항해계획 미흡 · 수심 확인',law:'해사안전 관련 법령',articles:'안전운항 관련 조항',score:89,office:'동해지방해양안전심판원',date:'2024.05.20',pages:9,file:'동해해심_제2024-015호_재결서.pdf'},
 {id:'case-6',no:'제2024-021호',title:'어선 바다누리호 기관손상사건',type:'기관손상',cause:'정비 불량',vessel:'어선',issues:'기관 점검 미흡 · 예방 정비',law:'선박안전 관련 법령',articles:'선박검사 및 설비 관련 조항',score:90,office:'부산지방해양안전심판원',date:'2024.07.02',pages:8,file:'부산해심_제2024-021호_재결서.pdf'},
];
const initial={
 chats:[{id:'chat-1',query:'석유제품운반선 12삼부호 사건 유사 판결 사례 검색해줘.',date:'2026-09-16',status:'완료',version:1,files:[]},{id:'chat-2',query:'제8서진호 충돌사건 관련 법령을 검색해줘.',date:'2026-09-15',status:'완료',version:1,files:[]},{id:'chat-3',query:'화물선 동해스타호 좌초사건의 원인을 요약해줘.',date:'2026-09-14',status:'완료',version:1,files:[]}],
 accidents:[{id:'acc-1',name:'석유제품운반선 12삼부호·어선 충돌사건',date:'2026-09-15',type:'충돌',status:'분석 완료',file:'12삼부호_사고조사보고서.pdf',missing:['당시 시정 정보','상대선 항적 자료'],summary:'항해 중인 석유제품운반선과 어선 사이에서 발생한 충돌사건의 예시 자료입니다. 양 선박의 경계 수행, 피항 시점, 충돌 위험 판단을 검토할 수 있습니다.'},{id:'acc-2',name:'화물선 동해스타호 좌초사건',date:'2026-09-14',type:'좌초',status:'확인 필요',file:'동해스타호_사고정보.hwp',missing:['사고 발생 좌표','수심 측정 기록'],summary:'항만 접근 중 발생한 좌초사건의 예시 자료입니다. 항로 계획과 당시 수심 자료가 추가로 필요합니다.'},{id:'acc-3',name:'어선 바다누리호 기관손상사건',date:'2026-09-12',type:'기관손상',status:'분석 완료',file:'바다누리호_사고보고서.pdf',missing:[],summary:'기관 운전 중 이상 징후와 정비 이력을 검토하기 위한 사고정보 예시입니다.'}],
 prompts:[{id:'prompt-1',title:'유사 재결사례 비교',category:'유사사례',text:'입력한 해양사고와 유사한 재결사례를 검색하고, 사고 유형·주요 쟁점·적용 법령을 표로 비교해줘.',date:'2026-09-15'},{id:'prompt-2',title:'사고 원인과 법령 분석',category:'관계법령',text:'이 사건의 주요 사고 원인과 관련 법령을 정리하고, 각 법령의 적용 사유와 출처를 함께 제시해줘.',date:'2026-09-14'},{id:'prompt-3',title:'누락 정보 점검',category:'사고분석',text:'첨부한 사고정보를 요약하고, 분석을 위해 추가 확인이 필요한 누락 정보를 알려줘.',date:'2026-09-12'}],
 promptHistory:[],
 notifications:[{id:'note-1',title:'사고정보 분석이 완료되었습니다.',body:'12삼부호 사고정보의 요약과 누락 정보를 확인할 수 있습니다. 사고정보 관리에서 상세 내용을 확인해 주세요.',date:'2026.09.16 09:42',type:'처리 결과',read:false},{id:'note-2',title:'추가 확인이 필요한 사고정보가 있습니다.',body:'동해스타호 사고의 발생 좌표와 수심 측정 기록이 누락되어 있습니다. 원문과 함께 확인해 주세요.',date:'2026.09.16 09:30',type:'확인 요청',read:false},{id:'note-3',title:'AI 응답 활용 안내',body:guardrail+' 표시된 분석·법령·재결서 내용은 실제 사건과 무관한 UI 예시입니다.',date:'2026.09.15 14:00',type:'공지',read:true}],
 settings:{scope:'전체 기간',sort:'유사도 높은 순',target:'전체 자료',threshold:80,length:'표준',format:'비교표',citations:true},
 draft:{title:'',accident:'acc-1',body:'',note:'',saved:''},collapsed:false,
};
let saved;try{saved=JSON.parse(localStorage.getItem('aaas-user-design-v1'));}catch{}
const state=saved?{...structuredClone(initial),...saved}:structuredClone(initial);
let route='home',chatId='',files=[],fileContext='query',job=null,timers=[],drawerReturn=null;
let filters={type:'전체 사고유형',cause:'전체 원인',law:'전체 법령'},listSearch='',historyStatus='전체 상태',fromDate='',toDate='',promptTab='saved',notificationTab='전체';
let sourceId='',sourcePage=1,sourceTab='summary',pending=null,pendingReturn=null,draftBusy=false;
const fileObjects=new Map();let toastTimer;
function persist(){try{localStorage.setItem('aaas-user-design-v1',JSON.stringify(state));return true;}catch{toast('현재 화면에 반영했습니다. 저장소를 사용할 수 없어 새로고침 시 초기화됩니다.');return false;}}
function toast(text){$('#user-toast').textContent=text;$('#user-toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#user-toast').classList.remove('show'),3300);}
function dateNow(){return new Date().toLocaleDateString('sv-SE');}
function uid(prefix){return prefix+'-'+Date.now()+'-'+Math.floor(Math.random()*1000);}
function heading(title,description,action='',kicker='ANALYSIS WORKSPACE'){return `<div class="page-heading"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${description}</p></div>${action}</div>`;}
function field(label,name,value='',optional=false,type='text'){return `<label class="field"><span>${label}<em class="${optional?'optional':'required'}">${optional?'선택':'필수'}</em></span><input type="${type}" name="${name}" value="${esc(value)}" ${optional?'':'required'}></label>`;}
function options(values,selected){return values.map(v=>`<option ${v===selected?'selected':''}>${esc(v)}</option>`).join('');}
function meta(rows){return `<dl class="detail-meta">${rows.map(([k,v])=>`<dt>${k}</dt><dd>${esc(v)}</dd>`).join('')}</dl>`;}
function info(text){return `<div class="info-note">${icon('info')}<span>${text}</span></div>`;}
function modal(title,body,footer='',wide=false){const d=$('#user-dialog');d.classList.toggle('wide',wide);d.innerHTML=`<div class="user-dialog-head"><h2 id="user-dialog-title">${esc(title)}</h2><button class="icon-btn" data-action="close-modal" aria-label="닫기">${icon('close')}</button></div><div class="user-dialog-body">${body}</div>${footer?`<div class="user-dialog-foot">${footer}</div>`:''}`;if(!d.open)d.showModal();}
function closeModal(){if(job?.stage==='delay')return;$('#user-dialog').close();}
function confirm(title,message,run,confirmLabel='확인'){
 pending=run;const d=$('#user-dialog');
 pendingReturn=d.open&&d.querySelector('form')?{html:d.innerHTML,fields:[...d.querySelectorAll('input,textarea,select')].map(el=>({name:el.name,value:el.value,checked:el.checked}))}:null;
 modal(title,`<p>${esc(message)}</p>`,btn('취소','cancel-confirm','close')+btn(confirmLabel,'confirm','check','primary'));
}
function drawer(title,body,kicker='REFERENCE CANVAS'){const d=$('#canvas-panel');if(d.hidden)drawerReturn=document.activeElement;d.innerHTML=`<div class="canvas-head"><div><div class="eyebrow">${kicker}</div><h2 id="canvas-title">${esc(title)}</h2></div><button class="icon-btn" data-action="close-canvas" aria-label="상세 패널 닫기">${icon('close')}</button></div><div class="canvas-body">${body}</div>`;d.hidden=false;$('#drawer-shade').classList.add('show');$('.user-shell').inert=true;$('.user-sidebar').inert=true;d.querySelector('button').focus();}
function closeDrawer(){const d=$('#canvas-panel');d.hidden=true;$('#drawer-shade').classList.remove('show');$('.user-shell').inert=false;$('.user-sidebar').inert=false;if(drawerReturn?.isConnected)drawerReturn.focus();}
function nav(){
 const items=[['history','search','채팅 검색'],['prompts','spark','프롬프트 관리'],['accidents','file','사고정보 관리'],['search','book','사고자료 검색'],['laws','scale','법령 정보 검색'],['draft','edit','재결서 작성 지원']];
 $('#user-nav').innerHTML=items.map(([r,i,n])=>`<a href="#${r}" class="nav-item ${route===r?'active':''}" ${route===r?'aria-current="page"':''} title="${n}">${icon(i)}<span class="nav-label">${n}</span></a>`).join('');
 $('#recent-chats').innerHTML=state.chats.slice(0,12).map(c=>`<div class="recent-chat ${chatId===c.id&&route==='chat'?'active':''}"><a href="#chat/${c.id}" title="${esc(c.query)}">${esc(c.query)}</a><button class="icon-btn" data-action="delete-chat" data-id="${c.id}" aria-label="대화 삭제">${icon('trash')}</button></div>`).join('');
 $('#chat-count').textContent=state.chats.length;$('#unread-dot').hidden=!state.notifications.some(n=>!n.read);
 const titles={home:'해양사고 분석 워크스페이스',chat:'AI 질의 · 응답',history:'질의 · 응답 이력',prompts:'나의 프롬프트',accidents:'사고정보 관리',search:'사고자료 검색',laws:'법령 정보 검색',draft:'재결서 작성 지원',settings:'사용자 맞춤 설정',notifications:'시스템 알림'};
 $('#page-context').textContent=titles[route];document.title=`${titles[route]} | AAAS`;
 document.body.classList.toggle('home-view',route==='home');document.body.classList.toggle('chat-view',route==='chat');document.body.classList.toggle('sidebar-collapsed',state.collapsed);
 $('#sidebar-toggle').setAttribute('aria-expanded',!state.collapsed);$('#sidebar-toggle').setAttribute('aria-label',state.collapsed?'메뉴 펼치기':'메뉴 접기');
}
function navigate(){
 const [next,id]=location.hash.slice(1).split('/');
 const allowed=['home','chat','history','prompts','accidents','search','laws','draft','settings','notifications'];
 route=allowed.includes(next)?next:'home';chatId=route==='chat'?id||state.chats[0]?.id:'';
 if(route==='chat'&&!state.chats.some(c=>c.id===chatId)){route='home';chatId='';}
 listSearch='';historyStatus='전체 상태';fromDate='';toDate='';filters={type:'전체 사고유형',cause:'전체 원인',law:'전체 법령'};
 document.body.classList.remove('mobile-open');closeDrawer();nav();render();window.scrollTo(0,0);
}
function render(){
 const pages={home:home,chat:chat,history:history,prompts:prompts,accidents:accidents,search:searchPage,laws:laws,draft:draft,settings:settings,notifications:notifications};
 $('#content').innerHTML=pages[route]();nav();
 if(route==='home'||route==='chat')updateFiles();
}
function composer(isHome=false){return `<div class="composer-wrap" data-drop="query"><div id="attachments" class="attachments"></div><form id="query-form" novalidate><div class="composer"><button type="button" class="attach-btn" data-action="attach" title="사고자료 첨부" aria-label="파일 첨부">${icon('plus')}</button><textarea id="query-input" name="query" rows="1" aria-label="질의 내용 (필수)" placeholder="AAAS에게 물어보기${isHome?' — 어떤 해양사고를 분석할까요?':''}" required></textarea><button type="submit" class="send-btn" aria-label="질의 전송">${icon('arrow')}</button></div><div id="query-error" class="inline-error" role="alert"></div><div id="suggestions" class="suggestions" hidden></div></form><div class="composer-help">${isHome?'<span>문서를 끌어 놓거나 + 버튼으로 첨부하세요.</span><span>Enter 전송 · Shift+Enter 줄바꿈</span>':`<span>${guardrail}</span>`}</div></div>`;}
function home(){return `<section class="home-content"><div class="hero-orb" aria-hidden="true"><div class="orb-halo"></div></div><div class="home-eyebrow">A SAFER SEA, A CLEARER INSIGHT</div><div class="home-heading"><span class="wordmark">AAAS</span><h1>AI 기반 해양사고 분석 시스템</h1></div><p class="hero-subtitle">흩어진 사고정보를 연결하고, 신뢰할 수 있는 분석의 근거를 찾습니다.</p>${composer(true)}<div class="quick-services">${[['laws','book','관련법령 찾기','사고와 관련된 법령과<br>적용 근거를 확인하세요.'],['sample-search','scale','유사사례 검색','닮은 사고의 재결사례를<br>비교하고 분석하세요.'],['draft','edit','재결서 작성 지원','사실관계와 쟁점을 정리해<br>초안 작성을 시작하세요.']].map(([a,i,t,d])=>`<button class="quick-service" data-action="${a}"><span class="service-icon">${icon(i)}</span><span><b>${t}</b><small>${d}</small></span>${icon('chevron')}</button>`).join('')}</div><div class="home-suggestion">이렇게 질문해 보세요 <button data-action="suggest-query" data-id="충돌사건의 유사 재결사례와 적용 법령을 비교해줘.">“충돌사건의 유사 재결사례와 적용 법령을 비교해줘.” ↗</button></div></section>`;}
function currentChat(){return state.chats.find(c=>c.id===chatId);}
function matchingCases(c=currentChat()){
 const q=c?.query||'';const type=q.includes('좌초')?'좌초':q.includes('기관')?'기관손상':q.includes('충돌')||q.includes('삼부')||q.includes('서진')?'충돌':null;
 let data=samples.filter(s=>(!type||s.type===type)&&s.score>=Number(state.settings.threshold));
 if(state.settings.scope==='최근 1년')data=data.filter(s=>s.date>='2025.09.16');
 if(state.settings.scope==='최근 3년')data=data.filter(s=>s.date>='2023.09.16');
 if(state.settings.target==='법령')data=[];
 if(state.settings.sort==='최신 재결 순')data.sort((a,b)=>b.date.localeCompare(a.date));else data.sort((a,b)=>b.score-a.score);
 return data.filter(s=>(filters.type==='전체 사고유형'||s.type===filters.type)&&(filters.cause==='전체 원인'||s.cause===filters.cause)&&(filters.law==='전체 법령'||s.law===filters.law));
}
function resultsFilter(){return `<div class="result-filter" id="result-filter"><select id="case-type" aria-label="사고유형 필터">${options(['전체 사고유형','충돌','좌초','기관손상'],filters.type)}</select><select id="case-cause" aria-label="사고 원인 필터">${options(['전체 원인',...new Set(samples.map(s=>s.cause))],filters.cause)}</select><select id="case-law" aria-label="법령 필터">${options(['전체 법령',...new Set(samples.map(s=>s.law))],filters.law)}</select>${btn('초기화','clear-case-filters','refresh','small')}</div>`;}
function caseTable(rows){return `<div class="result-table"><table><thead><tr><th>재결서</th><th>사고 유형</th><th>주요 쟁점 · 사례별 적용 법령</th><th>유사도</th></tr></thead><tbody>${rows.map((c,i)=>`<tr><td><button class="table-link" data-action="case-detail" data-id="${c.id}">${c.no}<small>${c.title}</small></button></td><td>${c.vessel}<small>${c.type}사건</small></td><td>${c.issues}<br><button class="row-law" data-action="case-laws" data-id="${c.id}">${icon('scale')}${c.articles}</button></td><td><button class="score ${i>1?'teal':i===1?'cyan':''}" data-action="case-detail" data-id="${c.id}" aria-label="${c.no} 유사도 ${c.score}% 상세">${c.score}%</button></td></tr>`).join('')||'<tr><td colspan="4"><div class="empty">조건에 맞는 예시 재결사례가 없습니다.<br>필터나 사용자 검색 설정을 변경해 주세요.</div></td></tr>'}</tbody></table></div>`;}
function resultCards(rows){return `<div class="result-card-list">${rows.map(c=>`<article class="surface"><div class="toolbar-actions" style="justify-content:space-between"><h3>${c.no} · ${c.vessel} ${c.type}</h3><span class="score">${c.score}%</span></div><p>${c.issues}</p><div class="toolbar-actions">${btn('사례 상세','case-detail','file','small',c.id)}${btn('적용 법령','case-laws','scale','small',c.id)}</div></article>`).join('')||'<div class="empty">조건에 맞는 예시 사례가 없습니다.</div>'}</div>`;}
function caseResults(){const rows=matchingCases();return `<div class="result-toolbar"><h2>유사 재결사례 <span>${rows.length}</span></h2><div class="toolbar-actions"><span class="subtle-label">유사도 ${state.settings.threshold}% 이상</span>${btn('필터','toggle-filters','filter','small')}</div></div>${resultsFilter()}<div id="case-result-list">${state.settings.format==='카드형'?resultCards(rows):caseTable(rows)}</div>`;}
function chat(){const c=currentChat();if(!c)return home();return `<section class="chat-page"><div class="query-row"><div class="query-bubble">${esc(c.query)}${c.files?.length?`<small>${icon('file')} ${c.files.map(f=>esc(f.name)).join(' · ')}</small>`:''}</div><div class="answer-heading"><div class="answer-symbol">${icon('spark')}</div><span>AAAS</span><small><i></i> 예시 응답 · ${c.version>1?'재생성 v'+c.version:'해양사고 분석'}</small></div><div id="answer-content">${job?.chat===c.id?progressHTML():c.status==='완료'?answer(c):incomplete(c)}</div></section><div class="chat-composer"><div class="chat-composer-inner">${composer()}</div></div>`;}
function answer(c){const rows=matchingCases(c);const type=c.query.includes('좌초')?'좌초':c.query.includes('기관')?'기관손상':'충돌';
 return `<div class="answer-intro"><h1>${c.version>1?'질의를 보완하여 분석 결과를 정리했습니다.':'유사 재결 사례를 검색했습니다.'}</h1><p>${state.settings.length==='간결'?`관련 ${type}사례의 쟁점과 법령을 비교했습니다.`:`${type}사건 분석을 위해 <b>사고 유형, 주요 원인, 적용 법령</b>을 기준으로 예시 재결사례를 비교했습니다. ${type==='충돌'?'경계 수행, 충돌위험 판단, 피항 협력':'사고 발생 경위와 예방 조치'}를 중심으로 검토할 수 있습니다.`}${c.files?.length?`<br>첨부 자료 <b>${c.files.length}개</b>가 질의에 연결되었습니다. 파일 본문 분석은 연결되지 않은 시안입니다.`:''}${state.settings.length==='상세'?'<br>각 사례의 사실관계와 원인 판단은 원문 패널에서 구분하여 확인할 수 있습니다. 자료가 부족한 사항은 추가 확인이 필요한 항목으로 표시합니다.':''}</p></div><div id="case-results">${caseResults()}</div><section class="result-section"><h2>적용 가능성을 검토할 법령</h2><div class="law-row"><span class="law-number">01</span><div><b>해사안전 관련 법령</b><p>사고 당시 적용 법령과 시행일을 확인하고 안전운항 관련 조항을 검토합니다.</p></div><button class="text-btn" data-action="law-detail" data-id="law-safety">관련 법령 ${icon('plus')}</button></div><div class="law-row"><span class="law-number">02</span><div><b>국제해상충돌예방규칙 (COLREG)</b><p>제5조 경계 · 제6조 안전속력 · 제7조 충돌위험 · 제8조 충돌 회피 동작</p></div><button class="text-btn" data-action="law-detail" data-id="law-colreg">관련 법령 ${icon('plus')}</button></div></section>${state.settings.citations?`<section class="result-section"><h2>답변의 근거 <span class="subtle-label">문서명 · 페이지 · 문단</span></h2><div class="source-grid">${(rows.length?rows.slice(0,3):samples.slice(0,1)).map((s,i)=>`<button class="source-card" data-action="case-original" data-id="${s.id}">${icon('file')}<span><b>${s.file}</b><small>3페이지 · 2문단<br>원문 미리보기 ↗</small></span></button>`).join('')}</div></section>`:''}<div class="answer-actions"><button data-action="regenerate">${icon('refresh')}응답 재요청</button><button data-action="compare">${icon('compare')}전·후 응답 비교</button><button data-action="copy-answer">${icon('copy')}복사</button><button data-action="save-as-prompt">${icon('bookmark')}프롬프트 저장</button></div><div class="answer-guardrail">${icon('shield')}<span>${guardrail}<br>재결사례·법령·유사도는 화면 설계용 예시이며 실제 사건의 판단 근거로 사용할 수 없습니다.</span></div><div class="follow-up"><button data-action="follow-up" data-id="이 사건의 주요 쟁점과 추가 확인이 필요한 정보를 정리해줘.">주요 쟁점 더 살펴보기 ↗</button><button data-action="draft">재결서 초안 작성하기 ↗</button></div>`;
}
function progressHTML(){if(!job)return '';const stages=['질의 이해','자료 검색','근거 분석','답변 생성'];return `<div class="process-box" role="status" aria-live="polite"><div class="process-top"><h2>${job.stage==='delay'?'처리가 예상보다 오래 걸리고 있습니다.':stages[Math.min(3,Math.floor(job.percent/26))]+' 중입니다.'}</h2><span class="spinner"></span></div><div class="progress-track" role="progressbar" aria-label="응답 생성 진행률" aria-valuenow="${job.percent}" aria-valuemin="0" aria-valuemax="100"><i style="width:${job.percent}%"></i></div><div class="process-steps">${stages.map((s,i)=>`<span class="${job.percent>=i*25?'done':''}">${job.percent>=(i+1)*25?'✓ ':''}${s}</span>`).join('')}</div><div class="process-actions"><span>진행률 ${job.percent}% · 응답 생성 시뮬레이션</span>${btn('정지','stop-query','stop','small')}</div></div>`;}
function incomplete(c){return `<div class="process-box ${c.status==='오류'?'error-box':''}"><div class="process-top"><h2>${c.status==='오류'?'응답을 생성하지 못했습니다.':'요청을 중지했습니다.'}</h2>${icon(c.status==='오류'?'alert':'stop')}</div><p>${c.status==='오류'?'검색 서비스 연결 오류 상황을 재현한 화면입니다. 질의와 첨부파일 정보는 유지됩니다.':'현재까지의 질의와 이력은 저장되었습니다. 필요하면 다시 요청해 주세요.'}</p><div class="form-actions">${btn('다시 요청','regenerate','refresh','primary')}</div></div>`;}
function clearTimers(){timers.forEach(clearTimeout);timers=[];}
function updateProgress(){if(route==='chat'&&currentChat()?.id===job?.chat)$('#answer-content').innerHTML=progressHTML();}
function startQuery(query,mode='normal',existing=false){
 if(job){toast('진행 중인 요청을 완료하거나 정지한 후 다시 시도해 주세요.');return;}
 clearTimers();let c;
 if(existing){c=currentChat();c.previous={version:c.version,summary:summaryText(c)};c.version++;c.status='처리 중';}
 else {c={id:uid('chat'),query:query.trim(),date:dateNow(),status:'처리 중',version:1,files:files.filter(f=>f.status==='완료').map(f=>({name:f.name,size:f.size}))};state.chats.unshift(c);}
 chatId=c.id;job={chat:c.id,percent:8,stage:'normal',mode};persist();files=[];
 if(location.hash===`#chat/${c.id}`){render();}else location.hash=`chat/${c.id}`;
 for(const [delay,percent] of [[450,27],[1000,53],[1600,76]])timers.push(setTimeout(()=>{if(!job)return;job.percent=percent;updateProgress();},delay));
 timers.push(setTimeout(()=>{
  if(!job)return;
  if(mode==='delay'){job.stage='delay';updateProgress();modal('응답이 지연되고 있습니다','<p>검색 결과를 준비하는 데 시간이 더 필요합니다. 현재 질의는 유지됩니다. 계속 기다리거나 요청을 정지할 수 있습니다.</p><div class="warning-note">응답 지연 상태를 확인하기 위한 시뮬레이션입니다.</div>',btn('정지','stop-query','stop')+btn('계속','continue-query','refresh','primary'));}
  else finishQuery(mode==='error'?'오류':'완료');
 },2200));
}
function finishQuery(status){if(!job)return;const c=state.chats.find(c=>c.id===job.chat);c.status=status;job=null;clearTimers();persist();if($('#user-dialog').open)$('#user-dialog').close();nav();if(route==='chat')render();}
function summaryText(c){return `${c.query}\n\n${c.version>1?'추가 검토: 사실관계 확인 및 사례별 적용 사유를 보완했습니다.':'사고 유형, 주요 원인, 적용 법령을 기준으로 예시 재결사례를 비교했습니다.'}\n${samples.filter(s=>c.query.includes('좌초')?s.type==='좌초':s.type==='충돌').map(s=>`${s.no} | ${s.vessel} | ${s.issues} | ${s.score}%`).join('\n')}\n\n${guardrail}\n※ 화면 검토용 예시 응답`}
function accidents(){return `<section class="workspace-page">${heading('사고정보 관리','분석할 사고자료를 모으고, 요약과 추가 확인이 필요한 정보를 검토하세요.',btn('사고정보 등록','accident-create','plus','primary'))}<div class="surface"><div class="filters"><input type="search" id="list-search" class="filter-search" placeholder="사고명 또는 파일명 검색" aria-label="사고정보 검색"><select id="accident-type" aria-label="사고 유형">${options(['전체 사고유형','충돌','좌초','기관손상'],filters.type)}</select><span class="list-count" id="list-count">총 <b>${state.accidents.length}</b>건</span></div><div id="list-body">${accidentRows()}</div></div><div style="margin-top:19px">${info('사고정보를 선택하면 요약·누락정보·원문을 우측 패널에서 확인할 수 있습니다. 모든 자료는 시안용 예시입니다.')}</div></section>`;}
function accidentRows(){const rows=state.accidents.filter(a=>(a.name+' '+a.file).includes(listSearch)&&(filters.type==='전체 사고유형'||a.type===filters.type));return `<div class="table-scroll"><table><thead><tr><th>사고명 · 첨부 문서</th><th>사고 유형</th><th>등록일</th><th>상태</th><th>관리</th></tr></thead><tbody>${rows.map(a=>`<tr><td><button class="table-link" data-action="accident-detail" data-id="${a.id}">${esc(a.name)}<small>${esc(a.file)}</small></button></td><td>${esc(a.type)}</td><td>${a.date}</td><td>${pill(a.status,a.status==='분석 완료'?'green':'orange')}</td><td><button class="text-btn" data-action="accident-detail" data-id="${a.id}">상세 ${icon('chevron')}</button></td></tr>`).join('')||'<tr><td colspan="5"><div class="empty">검색 결과가 없습니다.</div></td></tr>'}</tbody></table></div><div class="table-foot"><span>총 ${rows.length}건</span><span>사고정보와 첨부자료는 현재 브라우저에만 저장됩니다.</span></div>`;}
function accidentDetail(id,tab='summary'){const a=state.accidents.find(a=>a.id===id);if(!a)return;sourceId=id;sourceTab=tab;drawer('사고정보 상세',`${pill(a.status,a.status==='분석 완료'?'green':'orange')}<h3>${esc(a.name)}</h3>${meta([['사고 유형',a.type],['등록일',a.date],['원본 문서',a.file]])}<div class="tabs">${[['summary','요약'],['missing','누락정보 '+a.missing.length],['original','원문 미리보기']].map(([t,l])=>`<button class="tab ${tab===t?'active':''}" data-action="accident-tab" data-id="${t}">${l}</button>`).join('')}</div>${tab==='summary'?`<h4>사고 개요</h4><p>${esc(a.summary)}</p><h4>검토 포인트</h4><p>사고 경위와 원인 자료를 구분하고, 참고 사례와의 사실관계 차이를 확인합니다. 문서 내 사실을 검증한 뒤 분석에 활용해 주세요.</p>`:tab==='missing'?`<div class="missing-items"><b>${a.missing.length?'추가 확인이 필요한 정보':'등록된 누락 항목이 없습니다.'}</b><ul>${a.missing.map(m=>`<li>${esc(m)}</li>`).join('')}</ul></div><p>누락정보는 입력 자료에 따른 예시이며, 자동 문서 분석 결과가 아닙니다.</p>`:`${sourceMeta(a.file,'3페이지 · 2문단','사고정보 등록')}<div class="document-page"><div class="doc-label">ORIGINAL DOCUMENT · 예시</div><h3>사 고 정 보</h3><p><b>사고명</b> ${esc(a.name)}</p><p>${esc(a.summary)}</p><p><mark>사고 당시 상황 및 원인 자료는 추가 확인이 필요합니다.</mark></p><p>등록한 실제 파일 본문은 자동 추출하지 않습니다. 이 영역은 원문 전시 구성 예시입니다.</p></div>`}<div class="canvas-footer">${btn('정보 수정','accident-edit','edit','',id)}${btn('AI에게 질문','accident-query','spark','primary',id)}</div>`,'ACCIDENT INFORMATION');}
function sourceMeta(name,location,source){return `<div class="source-details"><b>${esc(name)}</b><br>위치: ${esc(location)}<br>출처: ${esc(source)}<br>문서 및 본문 내용은 시안용 예시입니다.</div>`;}
function caseDetail(id,tab='summary',page=3){const s=samples.find(s=>s.id===id);if(!s)return;sourceId=id;sourceTab=tab;sourcePage=Math.min(s.pages,Math.max(1,page));
 drawer('유사 재결사례',`${pill('유사도 '+s.score+'%')}<h3>${s.title}</h3>${meta([['사건·재결번호',s.no],['심판기관',s.office],['재결일',s.date+' (예시)'],['사고 유형',s.type],['주요 원인',s.cause]])}<div class="tabs">${[['summary','사례 요약'],['original','원문 미리보기'],['laws','적용 법령']].map(([t,l])=>`<button class="tab ${tab===t?'active':''}" data-action="case-tab" data-id="${t}">${l}</button>`).join('')}</div>${tab==='summary'?`<h4>사고 개요</h4><p>${s.vessel} 관련 ${s.type}사고의 사실관계와 재결 요지를 확인하는 예시입니다. 실제 재결 내용과 무관합니다.</p><h4>주요 쟁점</h4><p>${s.issues}를 중심으로 확인합니다. 현재 분석 대상과의 시정, 선박 상태, 항로 등 사실관계 차이를 검토해야 합니다.</p><div class="warning-note">유사도는 법적 판단의 일치 가능성이나 과실 비율을 의미하지 않습니다. 화면 표시용 값입니다.</div>`:tab==='laws'?`<div class="case-law-card"><h4>${s.law}</h4><p><b>관련 조항</b> · ${s.articles}</p><p><b>검토 근거</b> · ${s.issues}</p><p><b>적용 사유 예시</b> · 사고 당시 ${s.cause}와 관련된 행위 및 상황을 확인하기 위해 참고하는 조항입니다.</p><button class="text-btn" data-action="law-detail" data-id="${s.law.includes('국제')?'law-colreg':'law-safety'}">조항 상세 ${icon('chevron')}</button></div>`:`${sourceMeta(s.file,sourcePage+'페이지 · 2문단',s.office)}<div class="document-page"><div class="doc-label">ORIGINAL DOCUMENT · 예시</div><h3>${s.no} 재결서</h3><p><b>${sourcePage===1?'주 문':sourcePage<5?'이 유 · 사실관계':'원 인 판 단'}</b></p><p>${s.title}의 관련 문서를 표시하는 원문 미리보기 예시입니다.</p><p><mark>${sourcePage}페이지 2문단: ${s.issues}에 관한 사고 경위 및 판단 근거를 확인하는 위치입니다.</mark></p><p>출처 문서와 인용 문단의 연결을 검토할 수 있습니다. 여기에 표시된 문장은 실제 재결서의 인용문이 아닙니다.</p></div><div class="document-nav"><button class="btn small" data-action="source-prev" ${sourcePage===1?'disabled':''}>← 이전</button><span>${sourcePage} / ${s.pages}페이지</span><button class="btn small" data-action="source-next" ${sourcePage===s.pages?'disabled':''}>다음 →</button></div>`}<div class="canvas-footer">${tab!=='original'?btn('원본 문서 보기','case-original','file','',id):''}${btn('재결서 작성에 참고','use-case-draft','edit','primary',id)}</div>`,'CASE REFERENCE');}
function searchPage(){return `<section class="workspace-page">${heading('사고자료 검색','재결사례를 검색하고 원문의 페이지·문단까지 확인하세요.',btn('질의 설정','settings','settings'))}<div class="surface"><div class="filters"><input id="list-search" class="filter-search" type="search" placeholder="재결번호, 선박명, 사고 유형 검색" aria-label="사고자료 검색"><select id="accident-type" aria-label="사고 유형">${options(['전체 사고유형','충돌','좌초','기관손상'],filters.type)}</select>${btn('초기화','reset-list','refresh','small')}</div><div id="list-body">${searchRows()}</div></div><p class="settings-summary">시안 데이터 6건 · 검색 결과에서 재결서를 선택하면 우측 원문 패널이 열립니다.</p></section>`;}
function searchRows(){return caseTable(samples.filter(s=>(s.title+s.no+s.type).includes(listSearch)&&(filters.type==='전체 사고유형'||s.type===filters.type)));}
function history(){return `<section class="workspace-page">${heading('질의 · 응답 이력','지난 분석을 찾아 다시 확인하고, 대화를 이어가세요.')}<div class="surface"><div class="filters"><input id="list-search" type="search" class="filter-search" placeholder="질의 키워드 검색" aria-label="질의 이력 검색"><label>시작일<input type="date" id="date-from" aria-label="검색 시작일"></label><label>종료일<input type="date" id="date-to" aria-label="검색 종료일"></label><select id="history-status" aria-label="응답 결과 상태">${options(['전체 상태','완료','처리 중','중지','오류'],historyStatus)}</select>${btn('초기화','reset-list','refresh','small')}</div><div id="date-error" role="alert" class="inline-error" style="padding:0 20px"></div><div id="list-body">${historyRows()}</div></div></section>`;}
function historyRows(){const rows=state.chats.filter(c=>c.query.toLowerCase().includes(listSearch.toLowerCase())&&(historyStatus==='전체 상태'||c.status===historyStatus)&&(!fromDate||c.date>=fromDate)&&(!toDate||c.date<=toDate));return `<div class="table-scroll"><table><thead><tr><th>질의 내용</th><th>요청일</th><th>결과 상태</th><th>응답 버전</th><th>관리</th></tr></thead><tbody>${rows.map(c=>`<tr><td><a class="table-link" href="#chat/${c.id}">${esc(c.query)}<small>${c.files.length?'첨부자료 '+c.files.length+'개':'자연어 질의'}</small></a></td><td style="white-space:nowrap">${c.date}</td><td>${pill(c.status,c.status==='완료'?'green':c.status==='오류'?'red':'orange')}</td><td>v${c.version}</td><td><button class="icon-btn" data-action="delete-chat" data-id="${c.id}" aria-label="${esc(c.query)} 대화 삭제">${icon('trash')}</button></td></tr>`).join('')||'<tr><td colspan="5"><div class="empty">조건에 맞는 대화가 없습니다.</div></td></tr>'}</tbody></table></div><div class="table-foot"><span>총 ${rows.length}건</span><span>개인 질의 이력</span></div>`;}
function prompts(){const data=state.prompts.filter(p=>(p.title+p.text).includes(listSearch));return `<section class="workspace-page">${heading('나의 프롬프트','반복하는 질문은 저장하고, 필요한 순간에 다시 사용하세요.',btn('프롬프트 등록','prompt-create','plus','primary'))}<div class="surface" style="margin-bottom:20px"><div class="tabs"><button class="tab ${promptTab==='saved'?'active':''}" data-action="prompt-tab" data-id="saved">저장한 프롬프트 ${state.prompts.length}</button><button class="tab ${promptTab==='history'?'active':''}" data-action="prompt-tab" data-id="history">사용 이력 ${state.promptHistory.length}</button></div></div>${promptTab==='saved'?`<div class="prompt-grid">${data.map(p=>`<article class="surface prompt-card"><div>${pill(p.category)}</div><h2>${esc(p.title)}</h2><p>${esc(p.text)}</p><span class="prompt-date">저장일 ${p.date}</span><div class="form-actions"><div class="toolbar-actions"><button class="icon-btn" data-action="prompt-edit" data-id="${p.id}" aria-label="프롬프트 수정">${icon('edit')}</button><button class="icon-btn" data-action="prompt-delete" data-id="${p.id}" aria-label="프롬프트 삭제">${icon('trash')}</button></div>${btn('사용하기','prompt-use','arrow','small',p.id)}</div></article>`).join('')||'<div class="empty">저장한 프롬프트가 없습니다.</div>'}</div>`:`<div class="surface"><div class="table-scroll"><table><thead><tr><th>프롬프트명</th><th>사용 일시</th><th>질의 내용</th></tr></thead><tbody>${state.promptHistory.map(p=>`<tr><td>${esc(p.title)}</td><td>${esc(p.date)}</td><td>${esc(p.text)}</td></tr>`).join('')||'<tr><td colspan="3"><div class="empty">아직 사용 이력이 없습니다. 저장한 프롬프트의 사용하기를 선택하세요.</div></td></tr>'}</tbody></table></div></div>`}</section>`;}
function promptForm(id,fromQuery=false){const p=state.prompts.find(p=>p.id===id);modal(p?'프롬프트 수정':'프롬프트 저장',`<form id="prompt-form" data-id="${p?.id||''}">${field('프롬프트명','title',p?.title||'')}<label class="field"><span>분류 <em class="required">필수</em></span><select name="category">${options(['유사사례','관계법령','사고분석','작성지원'],p?.category)}</select></label><label class="field"><span>질의 내용 <em class="required">필수</em></span><textarea name="text" required>${esc(p?.text||(fromQuery?currentChat()?.query:''))}</textarea></label><div class="form-actions"><button class="btn" type="button" data-action="close-modal">취소</button><button class="btn primary" type="submit">${icon('bookmark')}저장</button></div></form>`);}
function laws(){return `<section class="workspace-page">${heading('법령 정보 검색','사고와 연결된 법령의 체계, 조항, 출처를 함께 확인하세요.')}<div class="two-col"><section class="surface card-pad"><h2>법령 체계도</h2><p>상위 법령에서 하위 규정까지 구조를 따라 확인합니다.</p><div class="hierarchy"><button class="law-node" data-action="law-detail" data-id="law-safety">해사안전 관련 법률<small>상위 법령 · 예시</small></button><span class="law-connector"></span><button class="law-node" data-action="law-detail" data-id="law-decree">시행령<small>대통령령</small></button><span class="law-connector"></span><div class="law-branches"><button class="law-node" data-action="law-detail" data-id="law-rule">시행규칙<small>부령</small></button><button class="law-node" data-action="law-detail" data-id="law-notice">행정규칙·고시<small>세부 기준</small></button></div></div><div class="info-note">${icon('info')}법령 관계는 체계도 UI 예시입니다. 실제 적용 법령과 위임 관계는 연동 시 확인해야 합니다.</div></section><section class="surface card-pad"><h2>재결사례별 적용 법령 통계</h2><p>등록된 예시 재결사례 6건 기준 · 복수 적용 가능</p>${[['국제해상충돌예방규칙',3,50],['해사안전 관련 법령',2,33.3],['선박안전 관련 법령',1,16.7]].map(([n,c,p])=>`<div class="stat-row"><div><span>${n}</span><b>${c}건 <span class="subtle-label">(${p}%)</span></b></div><div class="stat-bar"><i style="width:${p}%"></i></div></div>`).join('')}<p class="settings-summary">사례 상세에서 적용 조항·근거·적용 사유를 구분하여 제공합니다.</p></section></div><div class="surface" style="margin-top:22px"><div class="filters"><input class="filter-search" id="law-search" type="search" placeholder="법령명 또는 조항 검색" aria-label="법령 검색"><span class="subtle-label">법령 내용은 UI 구성용 예시입니다.</span></div><div id="law-list">${lawRows('')}</div></div></section>`;}
const lawData=[{id:'law-colreg',name:'국제해상충돌예방규칙 (COLREG)',article:'제5조 경계 · 제6조 안전속력 · 제7조 충돌위험 · 제8조 충돌 회피 동작',type:'국제규칙'}, {id:'law-safety',name:'해사안전 관련 법률',article:'안전운항 관련 조항',type:'법률'}, {id:'law-ship',name:'선박안전 관련 법률',article:'선박검사·설비 관련 조항',type:'법률'}, {id:'law-decree',name:'해사안전 관련 법률 시행령',article:'법률 위임 사항',type:'대통령령'}, {id:'law-rule',name:'해사안전 관련 법률 시행규칙',article:'시행 절차 및 서식',type:'부령'}, {id:'law-notice',name:'안전운항 관련 고시',article:'세부 운항 기준',type:'행정규칙'}];
function lawRows(q){return `<div class="table-scroll"><table><thead><tr><th>법령명</th><th>관련 조항</th><th>법령 구분</th><th>상세</th></tr></thead><tbody>${lawData.filter(l=>(l.name+l.article).toLowerCase().includes(q.toLowerCase())).map(l=>`<tr><td><button class="table-link" data-action="law-detail" data-id="${l.id}">${l.name}</button></td><td>${l.article}</td><td>${pill(l.type,'gray')}</td><td><button class="text-btn" data-action="law-detail" data-id="${l.id}">조항 보기 ${icon('chevron')}</button></td></tr>`).join('')||'<tr><td colspan="4"><div class="empty">검색된 법령이 없습니다.</div></td></tr>'}</tbody></table></div>`;}
function lawDetail(id,tab='article'){const l=lawData.find(l=>l.id===id)||lawData[1];sourceId=l.id;sourceTab=tab;drawer('법령 조항 상세',`${pill(l.type)}<h3>${l.name}</h3><div class="tabs">${[['article','조항 내용'],['source','원문·출처'],['history','개정 이력']].map(([t,n])=>`<button class="tab ${tab===t?'active':''}" data-action="law-tab" data-id="${t}">${n}</button>`).join('')}</div>${tab==='article'?`<h4>${l.article}</h4><p>사고 분석에서 관련 법령의 조항과 검토 항목을 확인하는 화면입니다. 경계, 안전운항, 선박 점검 등의 사실관계와 연결하여 조항을 표시합니다.</p><div class="warning-note">실제 법령 원문을 인용한 내용이 아닙니다. 조항의 정확한 문구와 적용 시점은 공식 원문에서 확인해야 합니다.</div><h4>사례별 적용 사유</h4><div class="case-law-card"><h4>제2023-018호 · 충돌사건 (예시)</h4><p>검토 쟁점: 사고 전 상대선 인지 시점과 충돌위험 판단 과정</p><p>참고 목적: 사고 당시 행위와 의무 이행 여부를 검토하는 근거 표시</p><button class="text-btn" data-action="case-laws" data-id="case-1">연결 사례 보기 ${icon('chevron')}</button></div>`:tab==='source'?`${meta([['문서명',l.name],['공포일','2023.01.01 (표시 형식 예시)'],['시행일','2023.07.01 (표시 형식 예시)'],['출처','국가법령정보센터 · 연동 예정'],['인용 위치',l.article]])}<div class="source-details">법령별 원문 링크를 연결할 영역입니다. 현재는 공식 사이트의 시작 페이지로 이동합니다.</div><a class="btn" href="https://www.law.go.kr/" target="_blank" rel="noopener noreferrer" style="margin-top:18px">${icon('link')}국가법령정보센터 열기 ↗</a>`:`<h4>개정 이력 표시 예시</h4><ul class="revision-list"><li>2023.07.01 · 시행 (예시)<br>안전운항 관련 조항 정비</li><li>2022.01.01 · 이전 버전 (예시)<br>개정 조항 대비 정보 확인</li></ul><div class="warning-note">실제 공포·시행·개정 이력은 법령 데이터 연동이 필요합니다.</div>`}`,'LEGAL REFERENCE');}
function notifications(){const items=state.notifications.filter(n=>notificationTab==='전체'||!n.read);return `<section class="workspace-page">${heading('시스템 알림','처리 결과와 확인이 필요한 안내를 모아 확인하세요.',btn('모두 읽음','read-all','check'))}<section class="surface"><div class="tabs">${['전체','읽지 않음'].map(t=>`<button class="tab ${notificationTab===t?'active':''}" data-action="notification-tab" data-id="${t}">${t}</button>`).join('')}</div><div class="notification-list">${items.map(n=>`<article class="notice-row ${n.read?'':'unread'}"><span>${icon(n.type==='확인 요청'?'alert':'bell')}</span><div><h2><button class="table-link" data-action="notification-detail" data-id="${n.id}">${esc(n.title)}</button></h2><p>${esc(n.type)} · ${esc(n.date)}</p></div><button class="icon-btn" data-action="notification-delete" data-id="${n.id}" aria-label="알림 삭제">${icon('trash')}</button></article>`).join('')||'<div class="empty">표시할 알림이 없습니다.</div>'}</div></section></section>`;}
function notificationDetail(id){const n=state.notifications.find(n=>n.id===id);if(!n)return;n.read=true;persist();nav();if(route==='notifications')render();modal('알림 상세',`${pill(n.type)}<h3 style="font-size:16px;line-height:1.8">${esc(n.title)}</h3><p>${esc(n.body)}</p><span class="subtle-label">${esc(n.date)}</span>`,btn('삭제','notification-delete','trash','danger',id)+btn('확인','close-modal','check','primary'));}
function settings(){const s=state.settings;return `<section class="workspace-page">${heading('사용자 맞춤 설정','질의의 검색 범위와 응답 표시 방식을 각각 설정하세요.')}<form id="user-settings-form"><div class="two-col"><section class="surface card-pad"><div class="eyebrow">QUERY SETTINGS</div><h2>질의 · 검색 설정</h2><p>어떤 자료에서, 어떤 기준으로 찾을지 설정합니다.</p><label class="field"><span>기본 검색 범위</span><select name="scope">${options(['전체 기간','최근 3년','최근 1년'],s.scope)}</select></label><label class="field"><span>검색 대상</span><select name="target">${options(['전체 자료','재결서','법령'],s.target)}</select></label><label class="field"><span>기본 정렬</span><select name="sort">${options(['유사도 높은 순','최신 재결 순'],s.sort)}</select></label><label class="field"><span>유사도 임계치</span><div class="range-row"><input type="range" name="threshold" id="threshold" min="50" max="99" step="1" value="${s.threshold}"><output class="range-value" id="threshold-value">${s.threshold}%</output></div><small>기준 이상인 예시 재결사례만 결과에 표시됩니다.</small></label></section><section class="surface card-pad"><div class="eyebrow">RESPONSE SETTINGS</div><h2>응답 설정</h2><p>분석 결과의 분량과 표현 형식을 선택합니다.</p><label class="field"><span>응답 길이</span><select name="length">${options(['간결','표준','상세'],s.length)}</select></label><label class="field"><span>표출 형식</span><select name="format">${options(['비교표','카드형'],s.format)}</select></label><label class="switch-row"><span>출처 카드 표시<small>문서명, 인용 페이지·문단, 원문 패널 연결</small></span><input name="citations" type="checkbox" ${s.citations?'checked':''}></label><p class="settings-summary">법적 판단 대체 금지 안내는 항상 표시됩니다.<br>검색·응답 설정은 현재 브라우저의 예시 결과에 적용됩니다.</p>${info('실제 검색 및 모델 생성 파라미터 연동은 별도 구현이 필요합니다.')}</section></div><div class="form-actions">${btn('기본값 복원','reset-settings','refresh')}<button type="submit" class="btn primary">${icon('check')}설정 저장</button></div></form></section>`;}
function draft(){const d=state.draft;const a=state.accidents.find(a=>a.id===d.accident)||state.accidents[0];return `<section class="workspace-page">${heading('재결서 작성 지원','사실관계와 법리 쟁점을 구분하고, 근거를 확인하며 초안을 작성하세요.',btn('초안 내보내기','export-draft','download'))}<div class="draft-layout"><aside class="surface card-pad draft-brief"><h2>초안 작성 방향</h2><label class="field" style="margin-top:20px"><span>분석 대상 사고 <em class="required">필수</em></span><select id="draft-accident">${state.accidents.map(x=>`<option value="${x.id}" ${x.id===a?.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><div><h3>01 · 주요 쟁점</h3><p>${a?.type==='좌초'?'항로 계획과 수심 확인, 사고 전 대응':'경계 수행, 상대선 인지, 사고 회피 시점'}</p></div><div><h3>02 · 적용 법령·근거</h3><button class="text-btn" data-action="case-laws" data-id="${state.draft.reference||(a?.type==='좌초'?'case-5':'case-1')}">사례별 적용 조항 및 사유 ${icon('chevron')}</button><p>각 조항과 사실관계의 연결을 구분해 작성합니다.</p></div><div><h3>03 · 과실 판단 검토 근거</h3><p>진술·항적·기록 간 불일치를 확인하고, 입증되지 않은 내용은 별도로 표시합니다. 과실 비율을 자동 확정하지 않습니다.</p></div><div><h3>04 · 추가 확인 사항</h3><ul>${(a?.missing?.length?a.missing:['등록 자료의 원문과 사실관계 재확인']).map(m=>`<li>${esc(m)}</li>`).join('')}</ul></div>${info('AI 초안은 심판관의 최종 법적 판단을 대체하지 않습니다.')}</aside><form id="draft-form" novalidate class="surface card-pad draft-editor"><div class="toolbar-actions" style="justify-content:space-between;margin-bottom:20px"><h2 style="margin:0">재결서 초안</h2><span class="draft-status" id="draft-status">${d.saved?'임시 저장됨 · '+esc(d.saved):'작성 전'}</span></div>${field('문서 제목','title',d.title)}<label class="field"><span>초안 내용 <em class="required">필수</em></span><textarea name="body" id="draft-body" required placeholder="작성 방향을 확인한 후 초안을 생성하거나 직접 작성하세요.">${esc(d.body)}</textarea></label>${field('검토 메모','note',d.note,true)}<div id="draft-progress"></div><div class="form-actions">${btn('AI 초안 생성','generate-draft','spark')}<button type="submit" class="btn primary">${icon('bookmark')}초안 저장</button></div></form></div></section>`;}
function preserveDraft(){if(route==='draft'&&$('#draft-form')){const f=$('#draft-form');state.draft.title=f.elements.title.value;state.draft.body=f.elements.body.value;state.draft.note=f.elements.note.value;}}
function saveDraft(){preserveDraft();const missing=!state.draft.title.trim()||!state.draft.body.trim();confirm(missing?'미완료 초안 저장':'초안 저장',missing?'문서 제목 또는 본문이 비어 있습니다. 미완료 상태로 임시 저장할까요?':'현재 초안을 이 브라우저에 저장할까요?',()=>{state.draft.saved=new Date().toLocaleString('ko-KR');persist();render();toast(missing?'미완료 초안을 임시 저장했습니다.':'초안을 저장했습니다.');},missing?'임시 저장':'저장');}
function generateDraft(){if(draftBusy)return;preserveDraft();const generate=()=>{draftBusy=true;$('#draft-status').textContent='작성 중';$('#draft-progress').innerHTML='<div class="info-note" role="status">사실관계 → 쟁점 → 근거 순서로 초안을 구성하는 중입니다.</div>';const target=state.draft.accident;setTimeout(()=>{const a=state.accidents.find(a=>a.id===target)||state.accidents[0];state.draft.title=state.draft.title||a.name+' 재결서 초안';state.draft.body=`[화면 설계용 예시 초안 — 최종 법적 판단 아님]\n\n1. 사건 개요\n${a.name}\n${a.summary}\n\n2. 주요 쟁점\n사고 전 상황 인지와 예방 조치의 적정성을 확인한다. 각 선박의 행위와 객관적 기록을 구분하여 검토한다.\n\n3. 관련 법령 및 검토 근거\n사례별 적용 법령 패널에서 관련 조항과 적용 사유를 확인한다. 사고 당시 시행 법령과 사실관계의 부합 여부를 검증한다.\n\n4. 판단을 위한 추가 확인\n${a.missing.length?a.missing.join(', '):'원문 및 진술 기록의 일치 여부'}\n\n5. 검토 의견\n확인되지 않은 사실과 과실 비율은 확정하지 않는다. 본 초안은 참고용이며 최종 판단은 심판관의 검토에 따른다.`;state.draft.saved='';draftBusy=false;persist();if(route==='draft')render();toast('예시 초안을 생성했습니다. 내용을 검토해 주세요.');},1700);};if(state.draft.body.trim())confirm('초안 다시 생성','현재 작성한 본문을 예시 초안으로 바꿀까요?',generate);else generate();}
function updateFiles(){const containers=document.querySelectorAll('#attachments, #upload-files');containers.forEach(el=>{el.innerHTML=files.map(f=>`<div class="file-chip"><button type="button" data-action="file-preview" data-id="${f.id}">${icon('file')}<span><span class="file-name">${esc(f.name)}</span><small>${f.status==='오류'?'처리 오류 · 재시도 가능':f.status==='완료'?'준비 완료':`준비 중 ${f.progress}%`} · ${(f.size/1024).toFixed(0)} KB</small>${f.status==='준비 중'?`<div class="upload-track" role="progressbar" aria-label="${esc(f.name)} 파일 준비" aria-valuenow="${f.progress}" aria-valuemin="0" aria-valuemax="100"><i style="width:${f.progress}%"></i></div>`:''}</span></button>${f.status==='오류'?`<button data-action="file-retry" data-id="${f.id}" aria-label="파일 준비 재시도">${icon('refresh')}</button>`:''}<button type="button" class="remove-file" data-action="file-remove" data-id="${f.id}" aria-label="${esc(f.name)} 첨부 제거">${icon('close')}</button></div>`).join('');});}
function prepareFile(f,fail=false){f.status='준비 중';f.progress=0;updateFiles();let p=0;const interval=setInterval(()=>{if(!files.includes(f)){clearInterval(interval);return;}p+=25;f.progress=p;if(p>=100){f.status=fail?'오류':'완료';clearInterval(interval);}updateFiles();},250);}
function attachFiles(incoming,fail=false){const rejected=[];for(const file of incoming){if(files.length>=5){rejected.push('최대 5개까지 첨부할 수 있습니다.');break;}if(!/\.(pdf|hwp|hwpx|docx|txt)$/i.test(file.name)){rejected.push(file.name+': 지원하지 않는 형식');continue;}if(file.size>50*1024*1024){rejected.push(file.name+': 50MB 초과');continue;}if(!file.size){rejected.push(file.name+': 빈 파일');continue;}const f={id:uid('file'),name:file.name,size:file.size,status:'준비 중',progress:0};files.push(f);fileObjects.set(f.id,file);prepareFile(f,fail);}if(rejected.length)modal('첨부파일을 확인해 주세요',`<p>${rejected.map(esc).join('<br>')}</p>${info('PDF, HWP, HWPX, DOCX, TXT · 파일당 최대 50MB · 최대 5개')}`,btn('확인','close-modal','check','primary'));}
async function filePreview(id){const f=files.find(f=>f.id===id);if(!f)return;let body=`<p>이 파일의 메타정보를 확인한 후 질의에 첨부할 수 있습니다.</p><div class="warning-note">${f.status==='오류'?'파일 준비 오류 예시입니다. 재시도를 선택해 주세요.':'PDF·한글·Word 본문 변환기는 연결되어 있지 않습니다. 실제 파일은 서버로 업로드하지 않습니다.'}</div>`;const actual=fileObjects.get(id);if(actual&&/\.txt$/i.test(f.name)){const content=await actual.text();body=`<div class="document-page"><pre class="file-preview-text">${esc(content.slice(0,18000))}</pre></div>`;}modal('첨부파일 미리보기',`${pill(f.status,f.status==='오류'?'red':'blue')}<h3 style="font-size:14px;overflow-wrap:anywhere">${esc(f.name)}</h3>${meta([['파일 크기',(f.size/1024).toFixed(1)+' KB'],['상태',f.status],['저장 범위','현재 화면 · 서버 전송 없음']])}${body}`,btn('확인','close-modal','check','primary'));}
function accidentForm(id){const a=state.accidents.find(a=>a.id===id);if(!a)files=[];fileContext='accident';modal(a?'사고정보 수정':'사고정보 등록',`<form id="accident-form" data-id="${a?.id||''}">${field('사고명','name',a?.name||'')}<div class="field-row"><label class="field"><span>사고 유형 <em class="required">필수</em></span><select name="type">${options(['충돌','좌초','기관손상'],a?.type)}</select></label>${field('사고일','date',a?.date||dateNow(),false,'date')}</div><label class="field"><span>사고 내용 <em class="optional">선택</em></span><textarea name="summary" placeholder="확인된 사실관계를 입력하세요.">${esc(a?.summary||'')}</textarea></label>${a?`<div class="source-details">첨부 문서: ${esc(a.file)}</div>`:`<div class="drop-zone" data-drop="accident">${icon('upload')}<br>사고자료를 여기에 끌어 놓으세요.<br><small>PDF · HWP · HWPX · DOCX · TXT / 최대 50MB</small><br><button type="button" class="text-btn" data-action="attach-accident">파일 선택 (선택)</button></div><div id="upload-files" class="attachments" style="margin-top:12px"></div>`}<div class="form-actions"><button type="button" class="btn" data-action="close-modal">취소</button><button type="submit" class="btn primary">${icon('check')}${a?'수정 저장':'등록'}</button></div></form>`);}
function scenarioModal(){modal('상태별 UI 확인','<p>정상·지연·오류 등 퍼블리싱 검토에 필요한 상태를 재현합니다.</p><div class="scenario-grid">'+[['scenario-normal','spark','정상 응답','질의 → 검색 → 분석 → 생성'],['scenario-delay','clock','응답 지연','계속 / 정지 선택 모달'],['scenario-error','alert','응답 오류','오류 안내와 재요청'],['scenario-upload','upload','파일 준비 정상','파일 준비 진행률과 완료'],['scenario-upload-error','file','파일 준비 오류','오류 및 재시도 버튼'],['scenario-empty','search','검색 결과 없음','조건에 맞는 결과가 없는 상태']].map(([a,i,t,d])=>`<button data-action="${a}">${icon(i)}<span>${t}<small>${d}</small></span></button>`).join('')+'</div>');}
function download(filename,content,type='text/plain;charset=utf-8'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function compare(){const c=currentChat();if(!c)return;if(!c.previous){modal('응답 전·후 비교','<p>아직 재생성한 응답이 없습니다. 응답 재요청을 실행하면 이전 답변과 비교할 수 있습니다.</p>',btn('취소','close-modal','close')+btn('응답 재요청','regenerate','refresh','primary'));return;}modal('응답 전·후 비교',`<p>같은 질의에 대한 답변 버전과 추가 검토 내용을 비교합니다.</p><div class="comparison"><article><h3>이전 답변 · v${c.previous.version}</h3><p style="white-space:pre-wrap">${esc(c.previous.summary)}</p></article><article><h3>현재 답변 · v${c.version}</h3><p style="white-space:pre-wrap">${esc(summaryText(c))}</p><div class="changed">보완 사항: 사실관계 추가 확인과 사례별 적용 사유를 구분했습니다. 화면 비교를 위한 예시 변경입니다.</div></article></div>`,btn('확인','close-modal','check','primary'),true);}
function refreshList(){if(route==='accidents')$('#list-body').innerHTML=accidentRows();if(route==='search')$('#list-body').innerHTML=searchRows();if(route==='history'){const invalid=fromDate&&toDate&&fromDate>toDate;$('#date-error').textContent=invalid?'종료일은 시작일보다 빠를 수 없습니다.':'';$('#list-body').innerHTML=invalid?'<div class="empty">검색 기간을 수정해 주세요.</div>':historyRows();}}
function saveWithConfirm(title,run){confirm(title,'입력한 내용을 현재 브라우저에 저장할까요?',()=>{run();persist();render();toast('저장했습니다.');},'저장');}
document.addEventListener('click',e=>{
 const target=e.target.closest('[data-action]');if(!target)return;const a=target.dataset.action,id=target.dataset.id;
 if(a==='sidebar'){if(innerWidth<=680)document.body.classList.toggle('mobile-open');else{state.collapsed=!state.collapsed;persist();nav();}return;}
 if(a==='close-modal'){closeModal();return;}
 if(a==='cancel-confirm'){pending=null;if(pendingReturn){$('#user-dialog').innerHTML=pendingReturn.html;for(const f of pendingReturn.fields){const el=[...$('#user-dialog').querySelectorAll('[name]')].find(el=>el.name===f.name);if(el){el.value=f.value;el.checked=f.checked;}}pendingReturn=null;}else closeModal();return;}
 if(a==='confirm'){const fn=pending;pending=null;pendingReturn=null;$('#user-dialog').close();fn?.();return;}
 if(a==='close-canvas'){closeDrawer();return;}
 if(['settings','notifications','laws','draft'].includes(a)){preserveDraft();closeDrawer();if($('#user-dialog').open)$('#user-dialog').close();location.hash=a;return;}
 if(a==='sample-search'){closeModal();if(state.chats.find(c=>c.id==='chat-1'))location.hash='chat/chat-1';else startQuery(initial.chats[0].query);}
 else if(a==='suggest-query'){const input=$('#query-input');input.value=id;$('#suggestions').hidden=true;input.focus();}
 else if(a==='follow-up')startQuery(id);
 else if(a==='attach'||a==='attach-accident'){fileContext=a==='attach'?'query':'accident';$('#attachment-input').click();}
 else if(a==='file-preview')filePreview(id);
 else if(a==='file-remove'){files=files.filter(f=>f.id!==id);fileObjects.delete(id);updateFiles();}
 else if(a==='file-retry'){const f=files.find(f=>f.id===id);if(f)prepareFile(f);}
 else if(a==='stop-query')finishQuery('중지');
 else if(a==='continue-query'){if(!job)return;job.stage='normal';job.percent=86;$('#user-dialog').close();updateProgress();timers.push(setTimeout(()=>finishQuery('완료'),1000));}
 else if(a==='regenerate'){if(job){toast('진행 중인 요청을 먼저 완료해 주세요.');return;}closeModal();startQuery(currentChat()?.query||'', 'normal',true);}
 else if(a==='compare')compare();
 else if(a==='copy-answer'){const c=currentChat();if(!c)return;const text=summaryText(c);if(navigator.clipboard)navigator.clipboard.writeText(text).then(()=>toast('응답을 복사했습니다.')).catch(()=>modal('응답 복사',`<label class="field"><span>내용을 선택하여 복사하세요.</span><textarea readonly>${esc(text)}</textarea></label>`));else modal('응답 복사',`<label class="field"><span>내용을 선택하여 복사하세요.</span><textarea readonly>${esc(text)}</textarea></label>`);}
 else if(a==='save-as-prompt')promptForm('',true);
 else if(a==='toggle-filters')$('#result-filter').classList.toggle('open');
 else if(a==='clear-case-filters'){filters={type:'전체 사고유형',cause:'전체 원인',law:'전체 법령'};$('#case-results').innerHTML=caseResults();$('#result-filter').classList.add('open');}
 else if(a==='case-detail')caseDetail(id);
 else if(a==='case-original')caseDetail(id,'original');
 else if(a==='case-laws')caseDetail(id,'laws');
 else if(a==='case-tab')caseDetail(sourceId,id,sourcePage);
 else if(a==='source-prev')caseDetail(sourceId,'original',sourcePage-1);
 else if(a==='source-next')caseDetail(sourceId,'original',sourcePage+1);
 else if(a==='law-detail')lawDetail(id);
 else if(a==='law-tab')lawDetail(sourceId,id);
 else if(a==='use-case-draft'){state.draft.reference=id;closeDrawer();location.hash='draft';toast('선택한 사례를 초안 참고자료로 연결했습니다.');}
 else if(a==='accident-create'){closeDrawer();accidentForm();}
 else if(a==='accident-edit'){closeDrawer();accidentForm(id);}
 else if(a==='accident-detail')accidentDetail(id);
 else if(a==='accident-tab')accidentDetail(sourceId,id);
 else if(a==='accident-query'){const acc=state.accidents.find(x=>x.id===id);closeDrawer();startQuery(acc.name+'의 유사 재결사례와 주요 쟁점을 분석해줘.');}
 else if(a==='delete-chat'){if(job?.chat===id){toast('진행 중인 대화는 정지한 후 삭제해 주세요.');return;}confirm('대화 삭제','이 질의와 응답 이력을 삭제할까요? 삭제 후에는 되돌릴 수 없습니다.',()=>{state.chats=state.chats.filter(c=>c.id!==id);persist();if(chatId===id)location.hash='home';else render();toast('대화를 삭제했습니다.');},'삭제');}
 else if(a==='reset-list'){listSearch='';filters.type='전체 사고유형';fromDate='';toDate='';historyStatus='전체 상태';render();}
 else if(a==='prompt-create')promptForm();
 else if(a==='prompt-edit')promptForm(id);
 else if(a==='prompt-delete')confirm('프롬프트 삭제','저장한 프롬프트를 삭제할까요? 사용 이력은 유지됩니다.',()=>{state.prompts=state.prompts.filter(p=>p.id!==id);persist();render();toast('프롬프트를 삭제했습니다.');},'삭제');
 else if(a==='prompt-tab'){promptTab=id;render();}
 else if(a==='prompt-use'){const p=state.prompts.find(p=>p.id===id);state.promptHistory.unshift({...p,date:new Date().toLocaleString('ko-KR')});persist();location.hash='home';setTimeout(()=>{if($('#query-input')){$('#query-input').value=p.text;$('#query-input').focus();}},0);}
 else if(a==='notification-tab'){notificationTab=id;render();}
 else if(a==='notification-detail')notificationDetail(id);
 else if(a==='notification-delete')confirm('알림 삭제','확인한 알림을 목록에서 삭제할까요?',()=>{state.notifications=state.notifications.filter(n=>n.id!==id);persist();render();toast('알림을 삭제했습니다.');},'삭제');
 else if(a==='read-all'){state.notifications.forEach(n=>n.read=true);persist();render();toast('모든 알림을 읽음 처리했습니다.');}
 else if(a==='reset-settings')confirm('설정 초기화','질의·응답 설정을 기본값으로 복원할까요?',()=>{state.settings=structuredClone(initial.settings);persist();render();toast('기본 설정으로 복원했습니다.');});
 else if(a==='generate-draft')generateDraft();
 else if(a==='export-draft'){preserveDraft();if(!state.draft.body.trim()){toast('내보낼 초안이 없습니다. 먼저 내용을 작성해 주세요.');return;}download((state.draft.title||'미완료_재결서_초안')+'.txt',state.draft.title+'\n\n'+state.draft.body+'\n\n검토 메모: '+state.draft.note+'\n\n'+guardrail);toast('초안을 TXT 파일로 내보냈습니다.');}
 else if(a==='export'){if(route==='chat'&&currentChat()){if(currentChat().status!=='완료'){toast('완료된 응답에서 내보내기를 사용할 수 있습니다.');return;}download('AAAS_질의응답.txt',summaryText(currentChat()));toast('질의응답을 TXT 파일로 내보냈습니다.');}else if(route==='draft'){$('[data-action="export-draft"]').click();}else modal('내보내기','<p>검색 결과에서는 질의와 응답을, 재결서 작성 화면에서는 초안을 TXT 파일로 저장할 수 있습니다.</p>',btn('예시 검색 결과 열기','sample-search','search','primary'));}
 else if(a==='scenarios')scenarioModal();
 else if(a.startsWith('scenario-')){closeModal();const mode=a.replace('scenario-','');if(mode==='empty'){location.hash='search';setTimeout(()=>{listSearch='검색결과없는자료';const input=$('#list-search');if(input){input.value=listSearch;refreshList();}},0);}else if(mode.startsWith('upload')){location.hash='home';const sample=new File(['화면 설계 검토용 사고정보 예시입니다. 실제 사고와 무관합니다.'],'사고정보_검토예시.txt',{type:'text/plain'});setTimeout(()=>attachFiles([sample],mode==='upload-error'),100);}else startQuery('석유제품운반선 12삼부호 사건 유사 판결 사례 검색해줘.',mode);}
});
document.addEventListener('input',e=>{
 const el=e.target;
 if(el.id==='query-input'){el.style.height='auto';el.style.height=Math.min(140,el.scrollHeight)+'px';const box=$('#suggestions');const q=el.value.trim();box.hidden=q.length<2;if(!box.hidden)box.innerHTML='<small>추천 프롬프트 · 선택하면 입력창에 적용됩니다.</small>'+[q+'의 유사 재결사례를 비교해줘.',q+'의 관련 법령과 출처를 알려줘.',q+'의 누락 정보를 확인해줘.'].map(t=>`<button type="button" data-action="suggest-query" data-id="${esc(t)}">${icon('spark')}${esc(t)}</button>`).join('');$('#query-error').textContent='';}
 if(el.id==='list-search'){listSearch=el.value;refreshList();}
 if(el.id==='law-search')$('#law-list').innerHTML=lawRows(el.value);
 if(el.id==='threshold')$('#threshold-value').textContent=el.value+'%';
 if(el.closest('#draft-form')){preserveDraft();$('#draft-status').textContent='저장하지 않은 변경 사항';}
});
document.addEventListener('change',e=>{
 const el=e.target;
 if(el.id==='attachment-input'){attachFiles([...el.files]);el.value='';}
 if(['case-type','case-cause','case-law'].includes(el.id)){filters[el.id.replace('case-','')]=el.value;const opened=$('#result-filter').classList.contains('open');$('#case-results').innerHTML=caseResults();if(opened)$('#result-filter').classList.add('open');}
 if(el.id==='accident-type'){filters.type=el.value;refreshList();}
 if(el.id==='history-status'){historyStatus=el.value;refreshList();}
 if(el.id==='date-from'){fromDate=el.value;refreshList();}
 if(el.id==='date-to'){toDate=el.value;refreshList();}
 if(el.id==='draft-accident'){preserveDraft();state.draft.accident=el.value;render();}
});
document.addEventListener('submit',e=>{
 e.preventDefault();const form=e.target,data=Object.fromEntries(new FormData(form));
 if(form.id==='query-form'){
  const q=data.query.trim();if(!q){$('#query-error').textContent='질의 내용을 입력해 주세요. (필수)';$('#query-input').focus();return;}
  if(files.some(f=>f.status!=='완료')){$('#query-error').textContent='첨부파일 준비가 완료되지 않았습니다. 오류 파일은 재시도하거나 제거해 주세요.';return;}
  $('#suggestions').hidden=true;startQuery(q);return;
 }
 if(form.id==='draft-form'){saveDraft();return;}
 for(const el of form.querySelectorAll('[required]'))if(!el.value.trim()){el.setCustomValidity('공백을 제외한 내용을 입력해 주세요.');el.reportValidity();el.addEventListener('input',()=>el.setCustomValidity(''),{once:true});return;}
 if(form.id==='prompt-form'){const id=form.dataset.id;saveWithConfirm(id?'프롬프트 수정':'프롬프트 저장',()=>{const p=state.prompts.find(p=>p.id===id);if(p)Object.assign(p,data);else state.prompts.unshift({id:uid('prompt'),...data,date:dateNow()});});}
 else if(form.id==='user-settings-form')saveWithConfirm('검색·응답 설정 저장',()=>{state.settings={...data,threshold:Number(data.threshold),citations:!!data.citations};});
 else if(form.id==='accident-form'){
  if(files.some(f=>f.status!=='완료')){toast('첨부파일 준비를 완료하거나 오류 파일을 제거해 주세요.');return;}
  const id=form.dataset.id,fileNames=files.map(f=>f.name).join(', ');saveWithConfirm(id?'사고정보 수정':'사고정보 등록',()=>{const a=state.accidents.find(a=>a.id===id);if(a)Object.assign(a,data);else state.accidents.unshift({id:uid('acc'),...data,summary:data.summary||'입력된 상세 내용이 없습니다. 원문과 사고 경위를 확인해 주세요.',status:'확인 필요',file:fileNames||'첨부 문서 없음',missing:['사고 경위 및 원인 검토','입력 자료의 완전성 확인']});files=[];});
 }
});
document.addEventListener('keydown',e=>{
 if(e.target.id==='query-input'&&e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('#query-form').requestSubmit();}
 if(e.key==='Escape'){if(!$('#user-dialog').open&&!$('#canvas-panel').hidden)closeDrawer();if($('#suggestions'))$('#suggestions').hidden=true;}
 if(e.key==='Tab'&&!$('#canvas-panel').hidden&&!$('#user-dialog').open){const list=[...$('#canvas-panel').querySelectorAll('a,button,input,select,textarea,[tabindex="0"]')].filter(x=>!x.disabled);const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}
});
document.addEventListener('click',e=>{if(!e.target.closest('.composer-wrap')&&$('#suggestions'))$('#suggestions').hidden=true;});
for(const ev of ['dragenter','dragover'])document.addEventListener(ev,e=>{if(e.dataTransfer?.types.includes('Files')){e.preventDefault();const zone=e.target.closest('[data-drop]');zone?.classList.add('dragging');}});
document.addEventListener('dragleave',e=>{const zone=e.target.closest('[data-drop]');if(zone&&!zone.contains(e.relatedTarget))zone.classList.remove('dragging');});
document.addEventListener('drop',e=>{if(e.dataTransfer?.files.length){e.preventDefault();document.querySelectorAll('.dragging').forEach(el=>el.classList.remove('dragging'));const zone=e.target.closest('[data-drop]');if(zone){fileContext=zone.dataset.drop;attachFiles([...e.dataTransfer.files]);}else toast('파일을 질의 입력창 또는 업로드 영역에 놓아 주세요.');}});
$('#user-dialog').addEventListener('cancel',e=>{if(job?.stage==='delay'){e.preventDefault();toast('계속 또는 정지를 선택해 주세요.');}});
$('#drawer-shade').onclick=closeDrawer;
$('#sidebar-toggle').innerHTML=icon('panel');$('.mobile-toggle').innerHTML=icon('menu');$('#new-chat-link').innerHTML=icon('edit')+'<span class="nav-label">새 채팅</span><span class="shortcut">＋</span>';
$('#new-chat-link').addEventListener('click',()=>{files=[];if(route==='home'){render();$('#query-input').focus();}});
$('#admin-icon').innerHTML=icon('grid');$('#settings-icon').innerHTML=icon('settings');$('#bell-icon').innerHTML=icon('bell');$('#export-button').innerHTML=icon('upload')+'내보내기';
window.addEventListener('hashchange',()=>{preserveDraft();navigate();});
window.addEventListener('beforeunload',()=>{preserveDraft();if(job){const c=state.chats.find(c=>c.id===job.chat);if(c)c.status='중지';}persist();});
state.chats.filter(c=>c.status==='처리 중').forEach(c=>c.status='중지');
navigate();
return {sampleCount:samples.length};
})();
